USE [master]
GO
--DROP DATABASE [CNPM]
CREATE DATABASE [CNPM]
GO
USE [CNPM]
GO

CREATE TABLE [ACCOUNT](
	USERNAME VARCHAR(100) PRIMARY KEY,	
	DISPLAYNAME VARCHAR(1000) NOT NULL DEFAULT 'EMPTY',
	PASSWORD VARCHAR(1000) NOT NULL,
	TYPE INT NOT NULL  DEFAULT 0 -- 1: admin && 0: accountant
)
GO
INSERT INTO [ACCOUNT] (USERNAME,DISPLAYNAME,PASSWORD,TYPE) VALUES 
('TRUNG20','Thanh Trung','01',1),
('THANHTRUNG20','Thanh Trung','01012000',0),
('TUONGVY79','Tuong Vy','01012000',0)
GO
CREATE TABLE [ACCOUNTANT](
	[ID_ACCOUNTANT] INT IDENTITY PRIMARY KEY,
	[NAME] [VARCHAR] (1000) NOT NULL DEFAULT 'EMPTY',
	[PHONE_NUMBER] INT NOT NULL DEFAULT 0,
	[ADDRESS] [VARCHAR] (1000) NOT NULL DEFAULT 'EMPTY'
);
GO

CREATE TABLE [GOODSCATEGORY](
	ID INT IDENTITY PRIMARY KEY,
	[NAME] [VARCHAR] (100) NOT NULL DEFAULT 'EMPTY'
);
GO
CREATE TABLE [GOODS](
	ID INT IDENTITY PRIMARY KEY,
	[NAME] [VARCHAR] (100) NOT NULL DEFAULT 'EMPTY',
	IDCATEGORY INT NOT NULL,
	[INVENTORY] [VARCHAR] (50) NOT NULL,
	[UPRICE_IMPORT] [INT] NOT NULL,
	[UPRICE_DELIVERY] [INT] NOT NULL,
	FOREIGN KEY (IDCATEGORY) REFERENCES dbo.[GOODSCATEGORY](ID)
);
GO
--IMPORT 
CREATE TABLE [ADDIMPORT](
	ID INT IDENTITY PRIMARY KEY,
	[name] [VARCHAR] (100) NOT NULL,
	STATUS INT NOT NULL DEFAULT 0
);
GO
CREATE TABLE [IMPORT](
	ID INT IDENTITY PRIMARY KEY,
	DATECHECKOUT DATE,
	IDADDIMPORT INT NOT NULL,
	STATUS INT NOT NULL DEFAULT 0,
	TOTALPRICE FLOAT,
	FOREIGN KEY (IDADDIMPORT) REFERENCES dbo.[ADDIMPORT](ID)
);
GO
CREATE TABLE [IMPORTINFOR](
	ID INT IDENTITY PRIMARY KEY,
	IDIMPORT INT NOT NULL,
	IDGOODS INT NOT NULL,
	[COUNT] INT NOT NULL,
	FOREIGN KEY (IDIMPORT) REFERENCES dbo.[IMPORT](ID),
	FOREIGN KEY (IDGOODS) REFERENCES dbo.[GOODS](ID)
);
GO
--EXPORT 
CREATE TABLE [ADDEXPORT](
	ID INT IDENTITY PRIMARY KEY,
	[name] [VARCHAR] (100) NOT NULL,
	STATUS INT NOT NULL DEFAULT 0
);
GO
CREATE TABLE [EXPORT](
	ID INT IDENTITY PRIMARY KEY,
	DATECHECKOUT DATE,
	IDADDEXPORT INT NOT NULL,
	STATUS INT NOT NULL DEFAULT 0,
	TOTALPRICE FLOAT,
	FOREIGN KEY (IDADDEXPORT) REFERENCES dbo.[ADDEXPORT](ID)
);
GO
CREATE TABLE [EXPORTINFOR](
	ID INT IDENTITY PRIMARY KEY,
	IDEXPORT INT NOT NULL,
	IDGOODS INT NOT NULL,
	[COUNT] INT NOT NULL,
	FOREIGN KEY (IDEXPORT) REFERENCES dbo.[EXPORT](ID),
	FOREIGN KEY (IDGOODS) REFERENCES dbo.[GOODS](ID)
);
GO

--INSERT "IMPORT" BUTTON
INSERT INTO [ADDIMPORT] ([NAME], STATUS) VALUES ('Import',0);
GO
CREATE PROC USP_GetAddList
AS SELECT * FROM dbo.ADDIMPORT
GO
--INSERT "EXPORT" BUTTON
INSERT INTO [ADDEXPORT] ([NAME], STATUS) VALUES ('Export',0);
GO
CREATE PROC USP_GetExportList
AS SELECT * FROM dbo.ADDEXPORT
GO


--Them Goods Catelogy
INSERT INTO [GOODSCATEGORY] ([NAME]) VALUES 
('Good for face'),
('Good for eyes'),
('Good for lip');
--Them Goods
INSERT INTO [GOODS]([NAME], IDCATEGORY,	[INVENTORY],[UPRICE_IMPORT],[UPRICE_DELIVERY]) VALUES
('BHA 2% TEA TREE',1,'400 BOTTLES',150000,190000),
('5% GLYCOLIC ACID',1,'600 BOTTLES',340000,380000),
('NIACINAMIDE 4%',1,'550 BOTTLES',450000,480000),
('SERUM HA B5',1,'200 BOTTLES',550000,600000),
('SUNSCREEN ABUIST 30SPF',1,'300 TUBES',200000,230000),
('BLACKAGE MICELLAR WATER',1,'150 BOTTLES',160000,185000),
('REJUVENATING EYE SERUM',2,'245 TUBES',100000,130000),
('RETINOL OBEGA 0.05',1,'460 TUBES',850000,900000),
('AZELAIC ACID 20%',1,'350 TUBES',300000,360000),
('CLASSIC LIP BALM COMAX',3,'600 JARS',30000,40000),
('LIP SCRUB VANILLA BEAN',3,'400 JARS',25000,30000),
('FLANSOME GLOWY LIP',3,'350 LIPSTICKS',240000,280000),
('AHB EYE CREAM',2,'250 TUBES',120000,140000),
('SUR.MEDIC EYE CREAM',2,'300 TUBES',300000,360000);
GO
INSERT INTO [ACCOUNTANT] ([NAME],[PHONE_NUMBER],[ADDRESS]) VALUES 
('NGUYEN VAN AN','0908554331','Hamlet 2, Dai Thanh commune, Quoc Oai district, Ha Noi city'),
('LE NGOC BINH','0909502662','246, street 8, Ward 6, Vo Gap district, Ho Chi Minh city'),
('TRAN MINH CUONG','0780112044','D09, A10 Apartment, Nguyen Chanh street, Yen Hoa ward, Cau Giay district, Ha Noi city'),
('PHAN ANH DUY','0330444555','217/19 Xo Viet Nghe Tinh Street, Ward 17, Binh Thanh District, Ho Chi Minh City'),
('BUI HUONG GIANG','0812499500','No. 117, 8/32 Alley, Ho Tung Mau street, Mai Dich Ward, Cau Giay district, Ha Noi');
GO 
--Create Procedure to Insert Import Bill
CREATE PROC USP_InsertImport
@IDADDIMPORT INT
AS 
BEGIN
	INSERT dbo.IMPORT(DATECHECKOUT,IDADDIMPORT, STATUS)
	VALUES (GETDATE(), @IDADDIMPORT,0)
END

GO
CREATE PROC USP_InsertImportInfor
@IDIMPORT INT, @IDGOODS INT, @COUNT INT
AS 
BEGIN
	DECLARE @isExitImportInfor INT
	DECLARE @goodsCount INT =1

	SELECT @isExitImportInfor = ID,@goodsCount = COUNT 
	FROM dbo.IMPORTINFOR 
	WHERE IDIMPORT = @IDIMPORT AND  IDGOODS = @IDGOODS

	IF (@isExitImportInfor >0)
	BEGIN
		DECLARE @newCount INT = @goodsCount + @COUNT
		IF (@newCount>0)
			UPDATE dbo.IMPORTINFOR SET COUNT = @goodsCount + @COUNT WHERE   IDGOODS = @IDGOODS
		ELSE
			DELETE dbo.IMPORTINFOR WHERE IDIMPORT = @IDIMPORT AND  IDGOODS = @IDGOODS
	END
	ELSE
	BEGIN
		INSERT dbo.[IMPORTINFOR](IDIMPORT,IDGOODS, [COUNT])
		VALUES (@IDIMPORT,@IDGOODS, @COUNT)
	END
	
END
GO
Create PROC USP_GetListBillByDate
@checkIn date, @checkOut date
AS 
BEGIN
	SELECT i.ID AS [Bill ID], i.TOTALPRICE AS [Total Price], i.DATECHECKOUT AS [Date Check out]
	FROM dbo.IMPORT AS i,dbo.ADDIMPORT AS a
	WHERE  i.DateCheckOut <= @checkOut AND i.status = 1
END
GO

--Create Procedure to Insert Export Bill
CREATE PROC USP_InsertExport
@IDADDEXPORT INT
AS 
BEGIN
	INSERT dbo.EXPORT(DATECHECKOUT,IDADDEXPORT, STATUS)
	VALUES (GETDATE(), @IDADDEXPORT,0)
END

GO
CREATE PROC USP_InsertExportInfor
@IDEXPORT INT, @IDGOODS INT, @COUNT INT
AS 
BEGIN
	DECLARE @isExitExportInfor INT
	DECLARE @goodsCount INT =1

	SELECT @isExitExportInfor = ID,@goodsCount = COUNT 
	FROM dbo.EXPORTINFOR 
	WHERE IDEXPORT = @IDEXPORT AND  IDGOODS = @IDGOODS

	IF (@isExitExportInfor >0)
	BEGIN
		DECLARE @newCount INT = @goodsCount + @COUNT
		IF (@newCount>0)
			UPDATE dbo.EXPORTINFOR SET COUNT = @goodsCount + @COUNT WHERE   IDGOODS = @IDGOODS
		ELSE
			DELETE dbo.EXPORTINFOR WHERE IDEXPORT = @IDEXPORT AND  IDGOODS = @IDGOODS
	END
	ELSE
	BEGIN
		INSERT dbo.[EXPORTINFOR](IDEXPORT,IDGOODS, [COUNT])
		VALUES (@IDEXPORT,@IDGOODS, @COUNT)
	END
	
END
GO
Create PROC USP_GetListBillByDate2
@checkIn date, @checkOut date
AS 
BEGIN
	SELECT e.ID AS [Bill ID], e.TOTALPRICE AS [Total Price], e.DATECHECKOUT AS [Date Check out]
	FROM dbo.EXPORT AS e,dbo.ADDEXPORT AS a
	WHERE  e.DateCheckOut <= @checkOut AND e.status = 1
END
GO
	






